---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.21
args:
  OP_RETH_VERSION: v1.5.1
  OP_NODE_IMAGE: ghcr.io/otternode-io/ott-op-stack-1103
  DA_SERVER_IMAGE: us-docker.pkg.dev/oplabs-tools-artifacts/images/da-server:latest
